language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - "$NTFCN_EMAIL"
  on_success: always
  on_failure: always
branches:
  only:
  - master
  - cjdgithub
env:
  global:
  - secure: O1F9oJAUMmqNPpoFMlbHeAogkFBI34h2X7LAvdS8yv1mim6Pk/jKlZb1mTlTyHxhiY9V6z4nDX4yoe/Lit02zMgIYFa02VQLK5zNylihWnNRpfDgq+XahpWgzj9IHFoO+r6VBwk3HRBcv0qPU5XT1ClRDjJoYbxcfEQEEHN30RI1d0CTURq7TR71rWd8lYac/drc2lbBHq0SKIJURqQcl1dY20560pMNFaTFCAdKnxoIIySIzhc40wri0D6iKsXiQEPsU66B6o+aaRxOwAFxatbF3yxRdT6tK4XAs5f/duZmXwGyRj2LOB/dHnnzMNbKabURnOM8Ed+TwDsRt8gUD0gSoyWw8qOHHvAniX6ZNIayvV/gfVyG5F0mdPd5I6kjDPM8xP2OhSMJQA9ovTEMsEyRGbSinIF1E96dtgkBqUzpz7NzhsFY0lGk1nGBn7icq/vEdfcbKR6hrXE2uXzCSsg6jSzxJzN3Z/j+n61YUp0d6Q6H5QuaA41CnQzBXIDXpQeg4ZcUj4U9D2dU4Py6f6CCdoAsVC9mvUqKSPcYqT3qVdKCpegFVlvt/oizcdzAUw3iFyfIJ9geKWgDeXocQCRNTJJm1FPDP31TtkVnlw3J+vqOCYwreT/3AEvKCebGS26rMhYgiqhqwhlBmgENbrhh55boN4j+jrc52BwPK9s=
  - secure: ICOQ6gjmkxxVvCr1znQ0/zWqy923+Kurh75EZs6WQ4zotaT1H8mXttoiE0mODMUZ16bODilYoagkSV2SUEe+U6m5zligj2vs8Wu4G2b5bNC0gdAhoQzrG2XgZH397c6EYV6aPEv0O8e7NMZzNYazXtmFVTTuNQOcGlXeQhOywwgVjpg/A5Xa5z9S5RreEWFLAqCXLXzNKRXB82rQkb4AL9TtpI5am6VGJ7LPiRP29GrwgdO00afgJzX8aQ9Z4TV3m3bt1J52X4NDfJc7Md0dBZ6tLMVhrk0KMsuesDXeePQ/uAkBu7Y0ABRTT3wivCB4ccwHB/Rveudwsc5VfaNhZ4WN6XJM+lNZa3NW6kQ0Avcdw0miWlYMpU5HhHKVfS6TC1A96TyBv85C2uXNdJlCwK0naUduk3hZeGlfeMhz+CHyQi03RwKhNPY+X5MrVYv2ZoPNqP5OxpRz5zS6XmRO1+XWRNAfYKdAFGLqmUdUxj6Na5Sjak9oJE7u9CMFVOScs87mK7NNzBVo1mY8sixSAJDiM4ZZ1/JF9OCi2mhL/6ly583NTtGaoZ28rws3NRoPlkgpxoIbfxajbbpX+2f4P3d7ReQ6kNPsCmLFx99+BSAhLjkUa482BHTdsXQNZRGXzFi519+g38I/bRBIq6G8i+dJ0tEZKiZ1J2h5BgR1kvM=
  - secure: FECBkrPZwLK1En9DQwoU4r4yfBqdYp3NuJyv6hBrFwiLz2OEJt9BX4En3aE3jkUvE+pNkCdm/HX+2VLwVPHRekFsgL2q4ih+YOxSoKM2c7zoIlRPzW/aKXvL0EVkF9T9FwFPweI0sI3UVWvoyb83SZE8ec8oJbgxchQwUoWV3aycH2sxhAwf4Sf2/yfEeI2sLWlhQIx9OVojzSA3hyyPPNr1DCsrE88mMacmrAy58hGkB+VZXVbkjdNP+Ess5Rb4TxbiPZquQ+Be/ZR9+ITJGXW/XkGVBpcGJNIOQ333XFIjKyWKxRX1jmTra0eFKv9TCF1PVY+DICDyimbSMaKskVD0K2ZMKPMehcmwEKiKNeaI6RzpHAGSAqh4IdKK1WkAQyUkuRESytohD9+lsocJeQFj1Y4UBwj6pP/q8tm7aYpMovBvjCG3PpEMvc7PBcKdhrh1Mn7SxJ7PZopbBbjUGXRtPUX5qn9WjUxN/RdEP4KvxjvCdxvpe352PKGGUk6O8qp4y+fQHYQCL9bBQFVcVpgiwyMkYMzCS8L7EZzwQpYev7QOTLZbuzcgg+4oaDt6OpzXJv7AGPQtPiL41Nr/dXpeXNnN4mpxZ75e5CRzbrpSBHHEIUPc6oDAB022Hu+3uv/0KInx27pjwxCRdFYq7BBYUMGcfGsDb22T2CqOX+0=
  - secure: ZgiIGGePTLF7M1E4T/mEFoe8dJBzxZXdowH9QGk0L1ynJcc7pcfPXirozqUHg4UPP2dXjJ/2PuzjM9+BUzDhHN2oYOMjrGK2YpzJZ4N6p3oijzIYJXabify1hE3uggcB7s0c1TvVTFEojDQOwoQn1+nPgwf1VCG0sl0ucqC45YqEM76yAKnLfXkKNifhi5jsPfQp7oe7qLpYq5c7bs77EjmhKiQ8h0TqCnMSm74gBGbWmVyUiZPUygC+sUKkONn9JYSn9hSVnN2d8bWNAtO1nUSPcHbALWXckmt+bmhsrqmHSjP4ZfWLAkjhjEexWYGo59Fdh0HyrNemiDC1lVtQux7WCmUJeoOfAtWZk6rrvUe5QMWRe2fdGD76eUeorR6jRxeKdPWsp6hYjxZrR98CxhYJN9lG9e/XSSNWjcBAm+2GDgLWk31UDufbUH7WOBZSlC/MKGVBJIVVhfjSOAs7/RC7wXyLagGALwhIGs9rDW/cWNTa1Vv1Yl+kJA93wNhCXl6O7f4SoGfDS27zIp5mhvznRPJqhmbJKh/rZQ3VRMNZSR7Z6nX7tXE5DdJ/4MFiQLaskGzlCfwShEJ253qHZIBiJweuohSIazmc9gtA0sA8vTIrN9YtgqnsywBL16QPCQFkvxunNc3PgYxTAZkoUJab1Kvk6s57pYWyc6vxoTw=
  - secure: Qq59Q+keikt98igAKLxpdyl/AAuEL3wOKJ6KxeYivzAS/oscalDLR+1OWIWzWt4OpNbJckj3n5YcQKZAwYvjxOwPYn01g2LU5X4kAMlnSm5L85i7i5Bj6KFoYdpTcmWEqWmvjdNUVamDvQvy4BsKxOhYDkPcdLJYWkNVLnxRt2/LN8iCRUOdzBvOiiI1XH9sGy6VCGvrPu8odkiGThHDULRT3QXAM5FUjOtdUDog30ptXdm0XjH797WMu5R1VgUMs73Yq6gPfctbyB7+ccM1c6P2cOHUx0oUQbcYq+JJECXus2OM8gniprBKxxVSkm8BEUa7kKtyFXrHa8/urkp3oNWVSL5Aq83LZ1eZ3ITvH4If5S9RP/ikEeqbiOIPqsKbMO10iqsFsaTjeaWj1BGV7irNnqURkMZHnwu/EH4ULzu9SMhHzmO0GaRyixLrBTG24F7qwlJb3tNhw4IHtzu8pmszLMAdXMX4QwsqutH1SEO50IiOqcAj+XojOtCs6br3yD4B1H9cNw3RbZHzOL3Mqb7IKmjtI2cSi4EPlZEeXUUxxszUhryZvWnMtpIdxduW5GsPEAjXBx/C7gbPie4O6k/1kBi5mmwAJTOlwx0ob5GvwISxInv0fbd9MQxz6n9PZQ6Lp8zNKHUDBe7XMrhVXyP6vaO+pvwAQYD0IVriqFs=
before_install:
- gem install travis -v 1.8.5 --no-rdoc --no-ri
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=54.215.193.139
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
